### ISSUE TITLE
Small typo in app/api/read /route.ts at l.15

### ISSUE THREAD

**Issue by louis-md** [dabit3/semantic-search-nextjs-pinecone-langchain-chatgpt#1]
Hi there 👋

Thanks for this awesome project. When running it I had to fix a small typo on app/api/read /route.ts at l.15. 

This line:

https://github.com/dabit3/semantic-search-nextjs-pinecone-langchain-chatgpt/blob/f4976466e3ccaf323542b0bf7823972f1b28d0d7/app/api/read/route.ts#LL15C1-L16C1

Should be:
  
```const indexName = 'my-test-index-2'```

Cheers

**Comment by dabit3** [comment]
Thank you @louis-md !
